macos-icon = "glass"
maximize = true
background-blur = 9
font-size = 13
font-family = "JetBrains Mono"
keybind = "shift+enter=text:\n"
theme = "dark:vague,light:Catppuccin Latte"
macos-titlebar-style = "tabs"
clipboard-write = "allow"
