apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rss-db
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cnpg
  path: ./k3s/clusters/dev/apps/rss-db
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: rss
      namespace: rss
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rss
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: rss-db
    - name: internal-gateway
  path: ./k3s/clusters/dev/apps/rss
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: rss
      namespace: rss
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bookmarks-db
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cnpg
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./k3s/clusters/dev/apps/bookmarks-db
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: bookmarks-db
      namespace: bookmarks
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bookmarks
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: bookmarks-db
    - name: public-gateway
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./k3s/clusters/dev/apps/bookmarks
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: bookmarks-backend
      namespace: bookmarks
    - apiVersion: apps/v1
      kind: Deployment
      name: bookmarks-frontend
      namespace: bookmarks
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tasks-db
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cnpg
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./k3s/clusters/dev/apps/tasks-db
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: tasks-db
      namespace: tasks
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tasks
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: tasks-db
    - name: public-gateway
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./k3s/clusters/dev/apps/tasks
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: tasks-frontend
      namespace: tasks
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: money-db
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cnpg
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./k3s/clusters/dev/apps/money-db
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: money-db
      namespace: money
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: money
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: money-db
    - name: public-gateway
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./k3s/clusters/dev/apps/money
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: money
      namespace: money
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-db
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cnpg
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./k3s/clusters/dev/apps/keycloak-db
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: keycloak-db
      namespace: keycloak
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: keycloak-db
    - name: internal-gateway
    - name: public-gateway
    - name: cert-manager
  path: ./k3s/clusters/dev/apps/keycloak
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: keycloak
      namespace: keycloak
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radicale
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: internal-gateway
    - name: volsync
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./k3s/clusters/dev/apps/radicale
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: radicale
      namespace: radicale
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weather
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: democratic-csi
    - name: volsync
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./k3s/clusters/dev/apps/weather
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: weather
      namespace: weather
