apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  interval: 5m
  path: ./k3s/clusters/dev/infrastructure/kube-vip
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: kube-vip
      namespace: kube-system
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-vip-cloud-provider
      namespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  interval: 5m
  path: ./k3s/clusters/dev/infrastructure/democratic-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: democratic-csi
      namespace: democratic-csi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  path: ./k3s/clusters/dev/infrastructure/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: internal-ingress
  namespace: flux-system
spec:
  interval: 5m
  path: ./k3s/clusters/dev/infrastructure/internal-ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: traefik-internal
      namespace: internal-ingress
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cert-manager
  path: ./k3s/clusters/dev/infrastructure/cnpg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cloudnative-pg
      namespace: cnpg-system
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: plugin-barman-cloud
      namespace: cnpg-system
