apiVersion: v1
kind: Secret
metadata:
    name: papra-secrets
    namespace: papra
type: Opaque
data:
    AUTH_SECRET: ENC[AES256_GCM,data:9uzHkJ4ghFYH2+RGAFJ4TF48KMWv1eU8GRAnwsg3vz2bX+9Zq6QsJ71TFvPES5IE7FeZ4kKxtTTt4qS+71ufSu/iqtXCAMl5vfihYTPvZTs6hYKM1L1HCEcVNp72JhG03JGwZi+vHLeIojOl7c4HcTf5mLkR9lmpW//50+ps0Jk=,iv:fEE1ApR1kI6osblSmLehUOjOX25IlTWouhrtNKRvvvE=,tag:C/Comz5o1OXfCQCQZvdP4A==,type:str]
    AUTH_PROVIDERS_CUSTOMS: ENC[AES256_GCM,data:4MHeY0BVa5T2QJzgBPTIVo+X6Avq1QuloNc4cb5uupGd52jv+D8SCg04YYtgfgDC3Pftu+ik5YuXOISY0X85967XdLiuq07RkNQYeyc8DpVws8IlG0hDIrfH0rlMt/0Tc0Ik/VC15DmynUbkvFREOqNE2TXYNxu3zsORQNE0UhNKMZ9ywdYZ+cnKB4Q34W2LpuJoPb5K78gft0JwyDGMUEdLz2Ie9EnJtmJlLHJ4+AN1838KA9lkpThy/bMyUOIgVBOhzUnXjf10DXQBrCHcmh/gvyHgvBby6vWG0p/q+n4Iyt6EtIruLp+R/svsyEqw2orfOC8kX4Vuc0K/eRNCFQqML8AYhlAcfRo/yjYu3K2ofy/7QcpS58psLUoWzJtm8uovftzgo8AjIzai87Vi7JXlyOmeB8yCUfVbe5z/NLIvrNMi6b1YnNx1E0H74S2g6gYdxoCaFOLbdSJ+lDK3GgzgOjB0AOMaaI+ddsj6U72v8PT8+MlBo5pIunLmrVV8L2dPlxCIok5yQhfgj+7Ze3wumRa97eQYoDMotFQvXv9vLRJqE/y83Nwe9Hul/BzFhITVyKHAMNDcFsVTPVp+rjWW3NlExAJANlPE4w==,iv:crUyrL0RnbahjJco6UzPlbo750K9T7Awvnn00rw/8LA=,tag:gmYX2dFI5do720BvNwxhFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNHNzd2dFR3FaZXd2WEhX
            R0R1TlpoaXhBRVRuOWxvRHBvL2FCUm9QdFVNCmdQU0RnNXo5dGQzazFaMDRZa1ZZ
            NS9KSEtCZGtLU0NPaGdYUWQyNlltQ2MKLS0tIC9KYW9YWmFXWUg5Y2FNOTJPa3dw
            eHBUTkUwYmNVYUxPcTlHOGZjQi9sZDgKC0hjkY8aNBrSbmrfTpzaKDiCtmwIduaK
            cBRdKExMKTXv/OTLW7CP2DYPW1xeaIAfveinbT6fN6rDS4SQVO/1Eg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1thp7ryp69smykxuklnsexhpvhtqy7z407j82pz45eutdswwccuzs9s8wt5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T22:27:18Z"
    mac: ENC[AES256_GCM,data:n4pNK6sO1+RmilSh8/GZIDte5WThYYBC9g7daA1mYWP9R0DeCAjNUp+WNGyrJe7XkcbUCXe9Xfby7WdjPZTkwatq1CPJfYUrs58f4Wlw+fXYVXUHBJbl20VVIV09yb7ZgTEZ2MfIbbbiNqC9SpAu5Z2qpilzDlKthCL3xmmYsow=,iv:ns9OIsDDQiLfp0INZRXLC3WzkyLR02fprcEGnzjgNUY=,tag:+I9ItJ8xSEnGuTvyf7B01Q==,type:str]
    version: 3.13.2
