apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.35
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.35
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.35
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 1h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.29.1
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - control1
                    - control2
    resources:
      requests:
        memory: 256Mi
      limits:
        memory: 256Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
  namespace: cnpg-system
spec:
  interval: 5m
  dependsOn:
    - name: cloudnative-pg
  chart:
    spec:
      chart: plugin-barman-cloud
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - control1
                    - control2
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 128Mi
