apiVersion: v1
kind: Secret
metadata:
    name: weather-secrets
    namespace: weather
type: Opaque
data:
    RUST_LOG: ENC[AES256_GCM,data:Ddy4vkkYjKQ=,iv:PNJm0+TZ+uJzRdVNtQde/rbeJx4B0cA5mOWKnhzBzxc=,tag:WZk1LrEHD9N5fMsrNLpbRA==,type:str]
    SUMMARY_HOUR: ENC[AES256_GCM,data:gupnCA==,iv:q2JXAkqtZSx7Zq4fI2ecQEdXfBunKRDYVaencAPilUY=,tag:DNF15f7KsPxyuXCq1/gZRg==,type:str]
    VAPID_SUBJECT: ENC[AES256_GCM,data:e3M0ipOZi8tDI7mrR3aoJjrVIjwtcrP4ieGDgkHkpmBVaXUO,iv:tcm1RB/OLSDfvs2LICiluVGaZ4Ar0/hblXQFePToqGI=,tag:tJyFkks390XlGSQQzYiQcA==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:UqvOsVIc1j2zyroHNGJCPrkXiW1pgO/n/9RWayDkM9WVyUpyzHJc/++6PhSaGzh21E/cEf3y0QwfFpdRhd682Sna2pl/delAWzhHVoP9Fwl9nlnPnm3pXR6xTCFnQeHd2+FVgZ7D8x+bVsQ1u6mW/OkU0G4=,iv:8vqy5kn3qiO6GotIcq4HFuvux1dyKO42GMJpiReWWHo=,tag:SnyLV0MNOAioLCG3bUsPSA==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:AmLO/0jHu6UoUj8worTHNVv5tH/2tOvXity64SMmtGTmptkjvcf+GnVuMb2CRjGEg8+UCTogP6VuKV86,iv:8NgjgJkY7hD5/7b9HHEJbSHBE7TN9BbgnkpTMFcKoaA=,tag:Z/UlOUaFor1UWRWFCfLNrg==,type:str]
    FMI_SID: ENC[AES256_GCM,data:P12CFfOgH2U=,iv:+lxbbJn428uHwVLrlftKXgg9BHqIp69mTL6wcncwSb8=,tag:9d8/0DZVIbwS8fsG6ZchEQ==,type:str]
    FMI_SID_WIND: ENC[AES256_GCM,data:zBfJZeaJN3w=,iv:Vwe54VoZmrIXALNgx6qeeCDtQxKYq8Gx16lgLm6ZXww=,tag:6jUkLS4uVfckbkPQ4qTzDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6K0U4dUxZY2F2VGdWRUli
            cjBuVEQxQlN2bHlsTGptSHIwdC9wSUpSVkRZCk01cU9EOE02aHArckVaaDI0MmFL
            R2NEbGxvY1FrME44M2ZzeVVOQTgwTGsKLS0tIHV6OERvbWIrUytXQmljZ1BSQVpE
            cXFuUXlKYVpxQ1pZRVFNOXNxOXNzdWsKkiiTsNESiGViFm4w0O096g5ddKkXS9n9
            fjsIm3NiUZi2zpnIRD+YrJsEx5n2vbDcJgytC442ROHWJZKWCNZfjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1thp7ryp69smykxuklnsexhpvhtqy7z407j82pz45eutdswwccuzs9s8wt5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T16:48:45Z"
    mac: ENC[AES256_GCM,data:+z/k0OCsKML0GPuCH9MJCJlgsYrAsYeR+yqKwVUQR3qZTVwTPxIs35pAnniIl6D1cESPuzPFnS6ZuRz4R+/xHalZR9fMx0KlpvekDSFtC29bdX93+7ARnfHMgAbCPglBtU/agDr7bPzkgqsGQ7wbnelAP0E229G02ozeGMviIKU=,iv:pbGBnYwqUf78nn1IVW+obIqZTQZ+/edhqfc+FDT22XY=,tag:Chd7OzBPGlfkgmgW0X1uRA==,type:str]
    version: 3.13.2
