apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  url: oci://docker.io/envoyproxy
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/envoyproxy/gateway
  ref:
    tag: v1.9.2
  ignore: |
    /charts/gateway-helm/charts/crds/crds/generated/gateway.networking.k8s.io_*.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-crds
  namespace: flux-system
spec:
  interval: 24h
  path: ./charts/gateway-helm/charts/crds/crds/generated
  prune: false
  sourceRef:
    kind: GitRepository
    name: envoy-gateway
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: envoyproxies.gateway.envoyproxy.io
