apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-public-cluster
rules:
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
  - apiGroups: [gateway.networking.k8s.io]
    resources: [gatewayclasses]
    verbs: [get, list, watch]
  - apiGroups: [gateway.networking.k8s.io]
    resources: [gatewayclasses/status]
    resourceNames: [traefik-public]
    verbs: [update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-public-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-public-cluster
subjects:
  - kind: ServiceAccount
    name: traefik-public
    namespace: public-ingress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-public-namespaced
rules:
  - apiGroups: [""]
    resources: [services, configmaps, secrets]
    verbs: [get, list, watch]
  - apiGroups: [discovery.k8s.io]
    resources: [endpointslices]
    verbs: [get, list, watch]
  - apiGroups: [gateway.networking.k8s.io]
    resources:
      - backendtlspolicies
      - gateways
      - grpcroutes
      - httproutes
      - referencegrants
      - tlsroutes
    verbs: [get, list, watch]
  - apiGroups: [gateway.networking.k8s.io]
    resources:
      - backendtlspolicies/status
      - gateways/status
      - grpcroutes/status
      - httproutes/status
      - tlsroutes/status
    verbs: [update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-public
  namespace: public-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-public-namespaced
subjects:
  - kind: ServiceAccount
    name: traefik-public
    namespace: public-ingress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-public
  namespace: keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-public-namespaced
subjects:
  - kind: ServiceAccount
    name: traefik-public
    namespace: public-ingress
