apiVersion: v1
kind: Namespace
metadata:
  name: public-ingress
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.35
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.35
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.35
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-public
  namespace: public-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 41.6.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    rbac:
      enabled: false
    experimental:
      kubernetesGateway:
        enabled: true
    api:
      dashboard: false
    gateway:
      enabled: false
    gatewayClass:
      enabled: true
      name: traefik-public
    deployment:
      replicas: 2
    ingressClass:
      enabled: false
      name: traefik-public
      isDefaultClass: false
    providers:
      kubernetesCRD:
        enabled: false
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
        namespaces: [public-ingress, keycloak]
        labelSelector: app.kubernetes.io/instance=traefik-public-public-ingress
    ports:
      web:
        forwardedHeaders:
          trustedIPs: []
          insecure: false
      websecure:
        forwardedHeaders:
          trustedIPs: []
          insecure: false
    service:
      spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.50.8
        allocateLoadBalancerNodePorts: false
        externalTrafficPolicy: Local
