apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi-mutual-chap
    namespace: democratic-csi
type: Opaque
data:
    mutual_password: ENC[AES256_GCM,data:pnjDnIbQ1l7LwBRNlImv/cG6NkffU1e5,iv:TXMAcAauKgUOjFLGJ9m9OcA7SJJ+aJvxEHffsfhrRPg=,tag:BWR8hH1i+UVuwiRhWEgmXg==,type:str]
    mutual_userid: ENC[AES256_GCM,data:qDcELxL5VTn2fvD/Ayidkg==,iv:GpwkEmMqXsIsBcIfdCvyZ5hEvkjkWghsx/9asLdFD30=,tag:WIqW6Md69UYbzEw+tECivw==,type:str]
    node-db.node.session.auth.authmethod: ENC[AES256_GCM,data:gYLFcjLAJ9k=,iv:j9m6Bz8cSJ90hdl5HMGv/4clKXNfEQLL4jJQQcym6K4=,tag:8Sy7hV+NjWnEL8V6t5MOBA==,type:str]
    node-db.node.session.auth.password: ENC[AES256_GCM,data:W32YFuMfiuPd7qbdrAkhhO88DDJd7Hh8,iv:dJYWwK8pLthddbABNDK7tF9hdIAHVjZoyLxBOZr51dU=,tag:qDHXzM100ky1Ug5lvUJRyQ==,type:str]
    node-db.node.session.auth.password_in: ENC[AES256_GCM,data:FlB2mPusgNa7+RAGwbkBeHdJK1uRHHWe,iv:tXRUDKcLYkyaXOFrN8ClXhsICqTpJV9jOpzmMZTp5so=,tag:7/cCWQETpKHCIPvcLYVSTA==,type:str]
    node-db.node.session.auth.username: ENC[AES256_GCM,data:5MxQFz0boNKXBT2NC94EIg==,iv:LNuCUw5c4dHJiWvbLoHNqFmiGV6CSFHO5J9LifIBbJw=,tag:gdH3rM+AFpSxUaEgkeG+zg==,type:str]
    node-db.node.session.auth.username_in: ENC[AES256_GCM,data:n89eAbUojIuWLPy5EMz5gw==,iv:q3LVPvAubuhN29YKSBsJygjxIYC0hsdw1SnNZLYVIM4=,tag:DJE15kTGHqU05t1DIUDLzQ==,type:str]
    password: ENC[AES256_GCM,data:SgBJ3VjNB1Xl34qw7C7NuU1NroIAJIPZ,iv:RhQWmaZiXZPQx6lt6uQrNoIVFRFWPtetu1C3w0ZqDh8=,tag:s5DYdiyER/+C9e+8kqoxjg==,type:str]
    userid: ENC[AES256_GCM,data:IFNypTPliUtCvnlimv5AZw==,iv:0QbdMS+T6luctVK3rZQ+ob34eSRxhzrbFt8Epz5E/VI=,tag:rHoSAp+R+A7CtwH4HqAWxA==,type:str]
sops:
    age:
        - recipient: age1thp7ryp69smykxuklnsexhpvhtqy7z407j82pz45eutdswwccuzs9s8wt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1d1poS2lNMFM2YmxZM2Ru
            YkhHVmZYS3cySDkzaVBVK2lCbFVXRllOblhJCjUrbzdROFIrZW1uRHZtRXZycDNR
            cHYyeWNYdC8zYytKR0tJQVh2SGs3RVUKLS0tIDFsVXJGU2FhWldjYTRveWw0NkJK
            OG0rWkNoWjBpQ2V5T2FWUGNValhTOHMKrvxFBvzyZk/Ci5sVEq4AJ0F5RZ5PB7Ps
            O7r7gHQ+RpXS98rIAq5C9hsa0nHukIme7n0+5/gjnmvHYwyCfV40RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-04T10:35:45Z"
    mac: ENC[AES256_GCM,data:scGI8nTwgpVp6v9FQJEWT6f/NVaSgCtpkVduCyWboX8ThAzenC+P8+Lk1ukyI+FY1bYH/6T5yUSUAGtBazZLQlwyBSXzx86K/FuyVB5auIv8a6Xd3/A0r6tcDd6Ln1VnlKjxwjszyFvfQBlsxP+uAyRUYZVa/T4vfitKq+KJE6E=,iv:zNbBWfTkoL0NzGY2X1uROg7dwOWJEt7BBjG2814NlqU=,tag:OpROGXHG1f0AMp8z36sTsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
