# 26.1.5-0
FROM quay.io/keycloak/keycloak@sha256:be6a86215213145bfb4fb3e2b3ab982a806d00262655abdcf3ffa6a38d241c7c AS base

from base as builder
env KC_HEALTH_ENABLED=true
env KC_METRICS_ENABLED=true
env KC_DB=postgres
workdir /opt/keycloak
run /opt/keycloak/bin/kc.sh build

from base
copy --from=builder /opt/keycloak/ /opt/keycloak/
entrypoint ["/opt/keycloak/bin/kc.sh", "start", "--optimized"]

