apiVersion: v1
kind: Secret
metadata:
    name: tasks-secrets
    namespace: tasks
type: Opaque
stringData:
    SECRET: ENC[AES256_GCM,data:DzAA8uzLMIHmm2+szcHCW+9ofFJH8n609Qz7igiMl1vi+jdYdwJgjguuS7KYMcMyazqtswFnaKi0MrhW+rPbqThk/0cF26YDSP2qOc38U2bgGUSgGGQLUVmmvc9E7g9S2jrS5g==,iv:gClKn3Iw4ft9WrqswtU/m3qqCPfoDuGkal/3DsGwYxY=,tag:EVm9I+q02TJjkeYKENPR4w==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:C12UziMeJEnnyVbXfs1rdhoYo2WECHyb5eLt375F8DGA235pQXSlgfYMoT+xzGKTFM+ZyFdLJ1Xu3IEL3YB5MGOuTSFJ1qo=,iv:KwbjrZM2qPAWrxiXiHWU98LyXmstCqsx92IUO/Zj1JE=,tag:m1L3awtsYazuAjNrHT/o+w==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:acuZjoCfIyeSKQhJBDg9xunFSfEKlzOeMwB+v/QR6Y0kAiA=,iv:QrNX6Z0WLzzznpJYlvimoki7RwZHc7RqbT2l5UzpWek=,tag:ofYxE/jftLdLz/KT+bkCoQ==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:HbRvdcu2u2bsG3gULdLr1Oc3IUDQaxWgskvuYxdVZVcdLRsIGq5II3caXaTy99VwAs9P6KurEsV8Agjvdj34l37FJNOFOvIRB6RC/Br3kdIBYxYUWlRV,iv:WQ3wiChVBNdXv16EX3Exw09O2x9ePYzLpycK8ZONelg=,tag:Jt1Y6m+NENx6ELPqPpUTrA==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:3JwFO/TfuWr2i36ZPM+w01grz0UsXusJ1bGfd6ETJWlulkNCkGlVFYuXBg==,iv:XmhpPB1jnyzYI+3RotFxFTW3m10PSGcayIOGZuKqmsM=,tag:jFkVB5ApzgRgXBlleBd2VA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NEVkZk9DNFVONm5meVlO
            QWp2NldGbm8yZjByUE5MSndLeHRMQVJuTkNjCmI4UG1yVmx1L3ZDM0xnMkJRR3cv
            OERyeFJ0bVZycloxUVhTUDlacTRacjQKLS0tIG93cm9hUWQ2b2VMZGp4QUthRkVp
            MktuK2kxN0NLdVlMR2VUeXUvejhBZDQKeH7VbRbvPRSLPw4udg8KEyOet9x46qnh
            SgHV1KtOCy9gjKfaF/SpEUKDSb4wMAZjEWHeTbpuIn89cGcSkIq0dg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1thp7ryp69smykxuklnsexhpvhtqy7z407j82pz45eutdswwccuzs9s8wt5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T13:45:28Z"
    mac: ENC[AES256_GCM,data:zm+Ua8QFPD++ruBsQWi4YQzdruEO2hPJReDz8Zxh0ycvuHKSF68fXHe33FxTva/r8Yo6fNzgFo/3e8cjIUbsNxKrFtV+4FR8cDwNufEgad2BWPvP7iAkI5TKaT7mcz9HIGTfKIEVF2dG76728/3PW9vIobXkfUhHVGu8SRiXZWw=,iv:MpPk9U3QCthR0qNBxmMvFyFZvFsYJiH/o5xfSERFQJk=,tag:ou91H4NYNBu1l5IhJsqNbw==,type:str]
    version: 3.13.2
