apiVersion: v1
kind: Namespace
metadata:
  name: bookmarks
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: bookmarks-db
  namespace: bookmarks
spec:
  instances: 2
  bootstrap:
    initdb:
      database: bm
      owner: bm
      locale: en_US.utf8
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - control1
                  - control2
  storage:
    storageClass: local-path
    size: 2Gi
