apiVersion: v1
kind: Secret
metadata:
    name: bookmarks-secret
    namespace: bookmarks
type: Opaque
stringData:
    SECRET: ENC[AES256_GCM,data:XWWS0hweYO601pHHlvRI6FeM2Paii7LQWZmmQpsE3Wl4xoOJDAiTj9gp2If8n0pCsh9HKQDZaUfYzWYAestktQ==,iv:kDA2N46mNAn58wZOkXoGjijQSyXGV3SME6p+XO9xvIc=,tag:pfrOEPpbKxMyeYNytncu1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aXB1V1JER2Vwd0dOSEN5
            STJlSGhMc2NQTnQvN2VnN3N6OWw4bVg3T3prCm5FTkVaYU9kbm9jZUtyTDJId1ow
            ZjNtdEJITHJSZXQ5NUI5aDFNeWNsTDQKLS0tIFcwVzlmS1V5NXJEQmZpZUFtU3RF
            RXNEbnUzTVlCSEpKWkhNZGNKRm4yWVkKzhY5JLxwT0Feuj2spyHP8WlmY0SDWQGt
            y1TbJOtSoQg7p6NcYu3MqyRye1WreMTEEKaCyl3/HPfHU7jmGXj4zg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1thp7ryp69smykxuklnsexhpvhtqy7z407j82pz45eutdswwccuzs9s8wt5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T16:04:53Z"
    mac: ENC[AES256_GCM,data:CZrmzVfrlRtokBdxp0UPgIMVWGyC5DHTBW/Ny7IcYelIKTS7p3Jv8DV3oGRWuDQQIyPgjUA/zfi+zB+URFFFlYU5gW5XLOhtKPMlRLKQmrqZoJZGLfqbkWkw2n2XtagMeNLvzR/HM5ff7jNxpiRQQ9OAQ88kH9h5fuLF++dVFBM=,iv:94bvd//gtAFyeTuHZWIJC3rH+U+/37/JS8JboiDBc8Y=,tag:5xJUSOFfS/KFbFnBk9TYRg==,type:str]
    version: 3.13.2
