apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-admin
  namespace: internal-ingress
spec:
  secretName: tls-keycloak-admin
  dnsNames:
    - authadmin.internal.veetik.com
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare-prod
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radicale
  namespace: internal-ingress
spec:
  secretName: tls-radicale
  dnsNames:
    - dav.internal.veetik.com
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare-prod
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rss
  namespace: internal-ingress
spec:
  secretName: tls-rss
  dnsNames:
    - rss.internal.veetik.com
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare-prod
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: weather
  namespace: internal-ingress
spec:
  secretName: tls-weather
  dnsNames:
    - weather.internal.veetik.com
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare-prod
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: papra
  namespace: internal-ingress
spec:
  secretName: tls-papra
  dnsNames:
    - docs.internal.veetik.com
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare-prod
