apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: internal-gateway-system
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kubernetes-api
  namespace: internal-gateway-system
spec:
  podSelector: {}
  policyTypes: [Egress]
  egress:
    - to:
        - ipBlock:
            cidr: 10.43.0.1/32
      ports:
        - protocol: TCP
          port: 443
    - to:
        - ipBlock:
            cidr: 192.168.50.5/32
        - ipBlock:
            cidr: 192.168.50.6/32
        - ipBlock:
            cidr: 192.168.50.7/32
      ports:
        - protocol: TCP
          port: 6443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: internal-gateway-system
spec:
  podSelector: {}
  policyTypes: [Egress]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-proxy-config
  namespace: internal-gateway-system
spec:
  podSelector:
    matchLabels:
      control-plane: envoy-gateway
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: internal-ingress
          podSelector:
            matchLabels:
              app.kubernetes.io/name: envoy
              gateway.envoyproxy.io/owning-gateway-name: internal-gateway
      ports:
        - protocol: TCP
          port: 18000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: envoy-internal
  namespace: internal-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: envoy
      gateway.envoyproxy.io/owning-gateway-name: internal-gateway
  policyTypes: [Ingress, Egress]
  ingress:
    - ports:
        - protocol: TCP
          port: 10080
        - protocol: TCP
          port: 10443
  egress:
    - to:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values: [keycloak, radicale, rss]
          podSelector:
            matchExpressions:
              - key: app
                operator: Exists
      ports:
        - protocol: TCP
          port: 8000
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 5232
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: internal-gateway-system
          podSelector:
            matchLabels:
              control-plane: envoy-gateway
      ports:
        - protocol: TCP
          port: 18000
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
